#test

name: Name File

on: [workflow_dispatch]

jobs:
  namefile:
    name: ðŸš€ Build Filename
    runs-on: ubuntu-latest
    environment: 
      name: DEV
    steps:
      - name: Install Cordova
        run: |
          mkdir $(date +%y)$(date +%m)$(date +%d)abcprod
          mkdir test_$(date +%Y%m%d-%H:%M)
          ls -R
