name: Manage version Number
on: [workflow_dispatch]

jobs:
  namefile:
    name: ðŸš€ Manage version
    runs-on: ubuntu-latest
    environment: 
      name: DEV
    steps:
      - name: test
        uses: actions/checkout@v2
      - name: Find and Replace
        run: sed -i 's/version="0.0.1"/version="0.0.2"/' bobo.xml
      #- name: Push changes
      #  uses: ad-m/github-push-action@v0.6.0
      #  with:
      #    github_token: ${{ secrets.MY_KEY }}
      #    branch: main
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.MY_KEY }}
          
          
          
